[package]
name = "my-rocket-service"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["blocking"] }
rocket = "0.5"
rocket_codegen = "0.5"
#rocket_contrib = "0.5"
rocket_contrib = "0.4.0-rc.2"
